### ISSUE TITLE
Read AVI specs

### ISSUE THREAD

**Issue by ogdabou** [ogdabou/givemeashow_fileManager#26]

**Comment by Lenjyco** [comment]
Petite synthèse : 
- 3 formats AVI : 
  - AVI 1.0 : première & vieille version d'AVI
  - Open-DML : v1.02 (taille des fichiers illimités overhead réduit de 33%)
  - Fichiers hybrides : OpenDML + Index "d'héritage" -> raisons de compatibilité

Le pdf est une doc de spécification sur les différents headers(MainAVIHeader, StreamHeader list, ) et variable qui composent le format AVI. Les variables y sont détaillées (headers = structure C)
Il est noter les manips liés à certains format audio qui peuvent sont gênants, détails sur les sous titre et le Garbage AVI.
